on:
   push:
      branches:
         - main
         - blog
   pull_request:
      branches:
         - main
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v2
         - name: Simple step
           run: echo Simple step
         - name: Multiline step
           run: |
             echo Multiline
             echo step
