on:
   push:
      branches:
         - main
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - run: echo Simple step
         - run: |
            echo Multiline
            echo step
